### ISSUE TITLE
Project board for extension ideas

### ISSUE THREAD

**Issue by instagibbs** [bitcoin-inquisition/bitcoin#10]
Since there are a few ideas out there (including merged ones) on what the inquisition is implementing, I think a one-look place to keep track of proposals, and what stage they are considered to be on, would be helpful.

f.e. stages

Idea Evaluation
WIP Implementations
In Review for Inclusion
Active
Retired

Something like this?

**Comment by ajtowns** [comment]
"Evaluation" is meant to be the outcome of having a BIP merged into inquisition for a while, so I don't think that's the way to describe the first step; the main thing that should be gating inclusion in inquisition is whether it's maintainable / makes it too difficult to include other ideas, rather than whether it's a good idea per se. (I have to keep reminding myself of this, let alone anyone else)

Maybe make it:
 1. file an issue for a BIP giving a general overview with links to more resources as a "call for interest" and a place to raise any maintenance concerns / potential conflicts with other ideas early
 2. replace that with a WIP PR
 3. move the PR into a small/brief "ready for merge" queue, since we'll generally need to rebase other PRs each time a PR is merged (since they'll touch neighbouring lines in consensus/params.h or script/interpreter.h)
 4. once it's merged, create an "evaluation of bip xxx" issue (can be common across versions) for people to add test results, and include it in the "active" common

**Comment by instagibbs** [comment]
We may want to sketch out some language on what that subjective gatekeeping looks like. I was thinking about proposal maturity, say if the proposal is rapidly changing, or doing something that breaks general design guidelines. Nothing listed in the wiki even comes close to that level, so I don't think it will be a practical issue. 

Rest of the stages sound fine.

**Comment by ajtowns** [comment]
If the proposal is rapidly changing that definitely comes under "maintenance concerns" in my opinion

**Comment by ajtowns** [comment]
https://github.com/orgs/bitcoin-inquisition/projects/2/views/1

**Comment by instagibbs** [comment]
SGTM
